project:
  type: website
  preview:
    port: 4200
    browser: false

website:
  title: "zeytin"
  logo: images/olive_fav.png
  favicon: images/olive_fav.png
  navbar:
    background: secondary
    left:
      - href: index.qmd
        text: Ana Sayfa
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full

editor: visual

