project:
  type: website
  preview:
    port: 4200
    browser: false

website:
  title: "D3"
  favicon: images/olive_fav.png
  navbar:
    background: secondary
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

