{
  "hash": "93dbcd2b4fcaab3ef6c85448ead98792",
  "result": {
    "markdown": "---\ntitle: \"2022 Yıl Sonu Enflasyon Tahminleri\"\nauthor: Raif Serkan Albayrak\ndescription: \"2022 yılı sonu ve 2023 yıl başı itibariyle yıllık enflasyon oranlarında baz etkisi nedeniyle ilginç dinamiklerin oluşması beklenmektedir.\"\ndate: 2022-07-05\ncategories:\n  - Zaman Serisi\n  - R\n  - Modelleme\ncode-fold: true\nimage: \"img/preview.png\"\nlang: tr\ncode-line-numbers: false\ntoc-title: İçerik\n---\n\n\nAylık enflasyon verisinin kullanarak yıllık enflasyon hesaplaması üzerinden gidilerek ay bazında Temmuz 2022'den itibaren Ağustos 2023'e kadar yıllık enflasyonun nasıl değiştiği, bu süreç içinde ortalama enflasyon da hesaplanacak.\n\n\n::: {.cell warnings='false'}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(magrittr)\nlibrary(lubridate)\nlibrary(readxl)\nlibrary(scales)\nlibrary(gt)\n```\n:::\n\n\n## Veri\n\nVeri [evds](https://evds2.tcmb.gov.tr/index.php?/evds/serieMarket) sistemi üzerinden indirildi. Sol menüde Fiyat Endeksleri altında, Fiyat Endeksi (Tüketici)(2003=100)(TUİK)(Yeni Seri) verisi işaretlenip, orta menüde 0.GENEL opsiyonu seçilip, formül menüsünde *Yüzde Değişim* ve *Yıllık Yüzde Değişim* opsiyonları seçildikten sonra Ekle düğmesine basılır. Sağ menüde, Frekans olarak Aylık opsiyonu seçilir, Başlangıç Tarihi de 01-2004 seçilir. Son olarak apor Seçenekleri kısmında en sol icon olan **Rapor Oluştur** ikonu tıklandığında veri kaydedilmeye hazır olacak şekilde sayfada gösterilir. Bu aşamada seçilen verilerin finansal kodları da görünmektedir. Bu analizde kullanılacak verilerin kodları: TP FG J0-1 ve TP FG J0-3'tür. Veriye kolayca ulaşmak için [burayı](https://github.com/SerkanAlbayrak/d3/raw/master/content/posts/06_2022_yilsonu_enflasyon_tahminleri/EVDS.xlsx) tıklayabilirsiniz.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nEVDS <- read_excel(\"EVDS.xlsx\")[1:222,] #diğer satırlarda açıklmalar var.\n```\n:::\n\n\nVeri üzerinde ilk yapılacak işlem *Tarih* değişkenini R'a tanıtmak. Bu amaçla başlangıçta `Lubridate` kütüphanesi yüklenmişti. Metinden tarihe dönüştürme fonksiyonları için bu [hatırlama kağıdı](https://rawgit.com/rstudio/cheatsheets/main/lubridate.pdf) kullanılabilir.      \n\n:::{.callout-caution}\n## R içinde tarih değişkenleriyle işlemler ve format\n\nR içinde tarih değişkenleriyle işlemleri özetleyen bir yazıyı yakında yayınlanacaktır. Ayrıca tarih tipinde bir değişkenin grafiklerde veya raporlarda gösteriminde formatlanma opsiyonları için; `?strptime` kullanılabilir.\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nEVDS$Tarih <- ym(EVDS$Tarih)\ncolnames(EVDS)[2:3] <- c(\"Ay\",\"Yıl\")\nEVDS$Ay %<>% as.numeric() # %<>% is an assigment pipe operator.\nEVDS$Yıl %<>% as.numeric()\nEnflasyon <- EVDS\nEnflasyon <- Enflasyon |> mutate(Ay=Ay/100,Yıl=Yıl/100)\n\n\ntheme_set(theme_bw())\nggplot(Enflasyon,aes(x=Tarih))+\n  geom_line(aes(y=Yıl, color=\"Yıllık Enflasyon Oranı\"),size=1.8)+\n  geom_line(aes(y=Ay*6, color=\"Aylık Enflasyon Oranı\"))+\n  theme(legend.title = element_blank(),legend.position = \"top\")+\n  scale_y_continuous(labels = scales::percent,\n                     sec.axis = sec_axis(~./6, name=\"Aylık Enflasyon\",\n                                         labels = scales::percent))+\n  labs(x=\"Tarih\", y=\"Yıllık Enflasyon\")+\n  scale_color_manual(values = c(\"gray50\",\"orange1\"))\n```\n\n::: {.cell-output-display}\n![](enflasyon_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# PLOTLY ile Secondary Axis Kullanarak Aylık ve Yıllık Enflasyon\n# fig <- plot_ly(Enflasyon,type = \"scatter\",mode=\"lines\") |> \n#   add_trace(x=~Tarih,y=~Yıl,name=\"Yıllık Enflasyon Oranı\")\n# \n# ay <- list(\n#   overlaying = \"y\",\n#   side = \"right\",\n#   title = \"<b>Aylık</b> Enf. Oranı\")\n# \n# fig <- fig %>% add_trace(x = ~Tarih, y = ~Ay, \n#                          name = \"Aylık Enflasyon Oranı\", \n#                          yaxis = \"y2\", mode = \"lines\", type = \"scatter\")\n# \n# fig <- fig %>% layout(\n#   title = \"Yıllık - Aylık Enflasyon Oranı\", yaxis2 = ay,\n#   xaxis = list(title=\"Tarih \"),\n#   yaxis = list(title=\"<b>Yıllık</b> Enf. Oranı\")\n# )%>%\n#   layout(plot_bgcolor='#e5ecf6',\n#           xaxis = list(\n#             zerolinecolor = '#ffff',\n#             zerolinewidth = 2,\n#             gridcolor = 'ffff'),\n#           yaxis = list(\n#             zerolinecolor = '#ffff',\n#             zerolinewidth = 2,\n#             gridcolor = 'ffff')\n#           )\n# \n# fig\n```\n:::\n\n\n\n\n\n\n## Yıllık Enflasyonun Hesaplanması\n\nYıllık enflasyon oranı bilindiği üzere aylık enflasyon oranlarının bileşik faizi şeklinde hesaplanır. Bu hesaplamada 12 geçmiş 12 aylık pencere kullanılır ve her ay bu pencere bir adım ilerletilir.    \n\n$$\ne_t=\\prod_{i=0}^{11}\\left(1+a_{t-i}\\right)-1\n$$\n\nAşağıdaki tabloda bu mantıkla yapılan hesaplama sonuçları (son 6 gözlem) verilmiştir. Beklendiği gibi değerler açıklanan oranlarla aynıdır. Dolayısıyla artık önümüzdeki döneme yönelik aylık enflasyon tahminleri yaparak yıllık enflasyon ve ortalama yıllık enflasyon değerleri hesaplanabilir.\n\n::: {.cell}\n\n```{.r .cell-code}\nlagged <- function(x){\n  result <- 1\n  for (i in 1:12){\n    result <- result*(1+lag(x,i))\n  }\n  result-1\n}\n\nEnflasyon <- Enflasyon |> mutate(Hesap = lead(lagged(Ay)))\nson_index <- dim(Enflasyon)[1]\nx <- Enflasyon$Ay[(son_index-11):son_index]\ne <- prod(1+x)-1\nEnflasyon$Hesap[son_index] <- e\n\n##TABLO\ntail(Enflasyon) |> gt::gt() |> tab_header(\n  title = \"Enflasyon Oranları\",\n  subtitle = \"Aylık Bileşik Faiz Hesabı Olarak Yıllık Enflasyon\"\n) |> fmt_date(columns = Tarih,date_style = 5) |> \n  fmt_percent(columns = c(Ay,Yıl,Hesap),decimals = 3)\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"ojibboyyrl\" style=\"overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>html {\n  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;\n}\n\n#ojibboyyrl .gt_table {\n  display: table;\n  border-collapse: collapse;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#ojibboyyrl .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ojibboyyrl .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#ojibboyyrl .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 0;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#ojibboyyrl .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ojibboyyrl .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ojibboyyrl .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#ojibboyyrl .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#ojibboyyrl .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#ojibboyyrl .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#ojibboyyrl .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#ojibboyyrl .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#ojibboyyrl .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#ojibboyyrl .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#ojibboyyrl .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#ojibboyyrl .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#ojibboyyrl .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ojibboyyrl .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#ojibboyyrl .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#ojibboyyrl .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ojibboyyrl .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#ojibboyyrl .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#ojibboyyrl .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ojibboyyrl .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ojibboyyrl .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#ojibboyyrl .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#ojibboyyrl .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ojibboyyrl .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ojibboyyrl .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-left: 4px;\n  padding-right: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ojibboyyrl .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ojibboyyrl .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ojibboyyrl .gt_left {\n  text-align: left;\n}\n\n#ojibboyyrl .gt_center {\n  text-align: center;\n}\n\n#ojibboyyrl .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#ojibboyyrl .gt_font_normal {\n  font-weight: normal;\n}\n\n#ojibboyyrl .gt_font_bold {\n  font-weight: bold;\n}\n\n#ojibboyyrl .gt_font_italic {\n  font-style: italic;\n}\n\n#ojibboyyrl .gt_super {\n  font-size: 65%;\n}\n\n#ojibboyyrl .gt_two_val_uncert {\n  display: inline-block;\n  line-height: 1em;\n  text-align: right;\n  font-size: 60%;\n  vertical-align: -0.25em;\n  margin-left: 0.1em;\n}\n\n#ojibboyyrl .gt_footnote_marks {\n  font-style: italic;\n  font-weight: normal;\n  font-size: 75%;\n  vertical-align: 0.4em;\n}\n\n#ojibboyyrl .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#ojibboyyrl .gt_slash_mark {\n  font-size: 0.7em;\n  line-height: 0.7em;\n  vertical-align: 0.15em;\n}\n\n#ojibboyyrl .gt_fraction_numerator {\n  font-size: 0.6em;\n  line-height: 0.6em;\n  vertical-align: 0.45em;\n}\n\n#ojibboyyrl .gt_fraction_denominator {\n  font-size: 0.6em;\n  line-height: 0.6em;\n  vertical-align: -0.05em;\n}\n</style>\n<table class=\"gt_table\">\n  <thead class=\"gt_header\">\n    <tr>\n      <th colspan=\"4\" class=\"gt_heading gt_title gt_font_normal\" style>Enflasyon Oranları</th>\n    </tr>\n    <tr>\n      <th colspan=\"4\" class=\"gt_heading gt_subtitle gt_font_normal gt_bottom_border\" style>Aylık Bileşik Faiz Hesabı Olarak Yıllık Enflasyon</th>\n    </tr>\n  </thead>\n  <thead class=\"gt_col_headings\">\n    <tr>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\">Tarih</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\">Ay</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\">Yıl</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\">Hesap</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td class=\"gt_row gt_left\">January 1, 2022</td>\n<td class=\"gt_row gt_right\">11.104%</td>\n<td class=\"gt_row gt_right\">48.691%</td>\n<td class=\"gt_row gt_right\">48.691%</td></tr>\n    <tr><td class=\"gt_row gt_left\">February 1, 2022</td>\n<td class=\"gt_row gt_right\">4.809%</td>\n<td class=\"gt_row gt_right\">54.439%</td>\n<td class=\"gt_row gt_right\">54.439%</td></tr>\n    <tr><td class=\"gt_row gt_left\">March 1, 2022</td>\n<td class=\"gt_row gt_right\">5.464%</td>\n<td class=\"gt_row gt_right\">61.145%</td>\n<td class=\"gt_row gt_right\">61.145%</td></tr>\n    <tr><td class=\"gt_row gt_left\">April 1, 2022</td>\n<td class=\"gt_row gt_right\">7.248%</td>\n<td class=\"gt_row gt_right\">69.971%</td>\n<td class=\"gt_row gt_right\">69.971%</td></tr>\n    <tr><td class=\"gt_row gt_left\">May 1, 2022</td>\n<td class=\"gt_row gt_right\">2.981%</td>\n<td class=\"gt_row gt_right\">73.496%</td>\n<td class=\"gt_row gt_right\">73.496%</td></tr>\n    <tr><td class=\"gt_row gt_left\">June 1, 2022</td>\n<td class=\"gt_row gt_right\">4.952%</td>\n<td class=\"gt_row gt_right\">78.618%</td>\n<td class=\"gt_row gt_right\">78.618%</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\n\nAylık enflasyon oranlarının 2023 yılı Ağustos ayına kadar %2-%7 olduğu senaryolar için hesaplamalar yapıldığında,\n\n\n::: {.cell}\n\n```{.r .cell-code}\naa <- tibble()\nfor (i in 1:15){\n aa[i,\"Tarih\"] <- Enflasyon$Tarih[son_index]+months(i)\n}\n\n#Senaryo Girdilerini Kodla\nEstimates <- bind_rows(Enflasyon,aa) |> \n  mutate(Ay2=ifelse(is.na(Ay),0.02,Ay)) |> \n  mutate(Ay3=ifelse(is.na(Ay),0.03,Ay)) |> \n  mutate(Ay4=ifelse(is.na(Ay),0.04,Ay)) |> \n  mutate(Ay5=ifelse(is.na(Ay),0.05,Ay)) |> \n  mutate(Ay6=ifelse(is.na(Ay),0.06,Ay)) |> \n  mutate(Ay7=ifelse(is.na(Ay),0.07,Ay))\n\n#Yıllık Enflasyon Hesapla\nEstimates <- Estimates |> \n  mutate(Yıl2 = lead(lagged(Ay2))) |> \n  mutate(Yıl3 = lead(lagged(Ay3))) |> \n  mutate(Yıl4 = lead(lagged(Ay4))) |> \n  mutate(Yıl5 = lead(lagged(Ay5))) |> \n  mutate(Yıl6 = lead(lagged(Ay6))) |> \n  mutate(Yıl7 = lead(lagged(Ay7))) \n\ne.period <- dim(Estimates)[1]-son_index\nEstimates <- Estimates[-(son_index+e.period),]\n```\n:::\n\n\nBu varsayımlar sonucu hesaplanan yıllık enflasyon tahminleri elde edilir. Bu yazının hazırlandığı Temmuz 2022 ortalarında ekonomi Ekim 2021'den itibaren süren bir krizin tam da ortasında bulunmaktadır. Krizden ne zaman ve nasıl çıkılacağına dair herhangi bir gösterge veya umut da an itibariyle mevcut değildir. Bu şartlar altında enflasyonla ilgili öngörüler oluşturulurken iyimser olmayı gerektirecek hiçbir neden bulunmamaktadır. Aşağıdaki tabloda, gerçekçi senaryoların aylık enflasyonun en iyimser ihtimalle %4 olacağı durumlar olduğunu düşünüyoruz. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nEstimates[1:son_index,11:16] <- NA\nEstimates[Estimates$Tarih>my(\"August 2021\"),\n          c(\"Tarih\",\"Yıl\",\"Yıl2\",\"Yıl3\",\"Yıl4\",\"Yıl5\",\"Yıl6\",\"Yıl7\")] |> \n  gt::gt() |> tab_header(\n  title = \"Enflasyon Oranları\",\n  subtitle = \"Aylık Bileşik Faiz Hesabı Olarak Yıllık Enflasyon\") |> \n  fmt_date(columns = Tarih,date_style = 5) |> \n  fmt_percent(columns = c(Yıl,Yıl2,Yıl3,Yıl4,Yıl5,Yıl6,Yıl7),decimals = 3)\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"tajmmbyjub\" style=\"overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>html {\n  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;\n}\n\n#tajmmbyjub .gt_table {\n  display: table;\n  border-collapse: collapse;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#tajmmbyjub .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#tajmmbyjub .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#tajmmbyjub .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 0;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#tajmmbyjub .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#tajmmbyjub .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#tajmmbyjub .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#tajmmbyjub .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#tajmmbyjub .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#tajmmbyjub .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#tajmmbyjub .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#tajmmbyjub .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#tajmmbyjub .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#tajmmbyjub .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#tajmmbyjub .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#tajmmbyjub .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#tajmmbyjub .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#tajmmbyjub .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#tajmmbyjub .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#tajmmbyjub .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#tajmmbyjub .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#tajmmbyjub .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#tajmmbyjub .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#tajmmbyjub .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#tajmmbyjub .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#tajmmbyjub .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#tajmmbyjub .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#tajmmbyjub .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#tajmmbyjub .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-left: 4px;\n  padding-right: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#tajmmbyjub .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#tajmmbyjub .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#tajmmbyjub .gt_left {\n  text-align: left;\n}\n\n#tajmmbyjub .gt_center {\n  text-align: center;\n}\n\n#tajmmbyjub .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#tajmmbyjub .gt_font_normal {\n  font-weight: normal;\n}\n\n#tajmmbyjub .gt_font_bold {\n  font-weight: bold;\n}\n\n#tajmmbyjub .gt_font_italic {\n  font-style: italic;\n}\n\n#tajmmbyjub .gt_super {\n  font-size: 65%;\n}\n\n#tajmmbyjub .gt_two_val_uncert {\n  display: inline-block;\n  line-height: 1em;\n  text-align: right;\n  font-size: 60%;\n  vertical-align: -0.25em;\n  margin-left: 0.1em;\n}\n\n#tajmmbyjub .gt_footnote_marks {\n  font-style: italic;\n  font-weight: normal;\n  font-size: 75%;\n  vertical-align: 0.4em;\n}\n\n#tajmmbyjub .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#tajmmbyjub .gt_slash_mark {\n  font-size: 0.7em;\n  line-height: 0.7em;\n  vertical-align: 0.15em;\n}\n\n#tajmmbyjub .gt_fraction_numerator {\n  font-size: 0.6em;\n  line-height: 0.6em;\n  vertical-align: 0.45em;\n}\n\n#tajmmbyjub .gt_fraction_denominator {\n  font-size: 0.6em;\n  line-height: 0.6em;\n  vertical-align: -0.05em;\n}\n</style>\n<table class=\"gt_table\">\n  <thead class=\"gt_header\">\n    <tr>\n      <th colspan=\"8\" class=\"gt_heading gt_title gt_font_normal\" style>Enflasyon Oranları</th>\n    </tr>\n    <tr>\n      <th colspan=\"8\" class=\"gt_heading gt_subtitle gt_font_normal gt_bottom_border\" style>Aylık Bileşik Faiz Hesabı Olarak Yıllık Enflasyon</th>\n    </tr>\n  </thead>\n  <thead class=\"gt_col_headings\">\n    <tr>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\">Tarih</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\">Yıl</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\">Yıl2</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\">Yıl3</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\">Yıl4</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\">Yıl5</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\">Yıl6</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\">Yıl7</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td class=\"gt_row gt_left\">September 1, 2021</td>\n<td class=\"gt_row gt_right\">19.583%</td>\n<td class=\"gt_row gt_right\">NA</td>\n<td class=\"gt_row gt_right\">NA</td>\n<td class=\"gt_row gt_right\">NA</td>\n<td class=\"gt_row gt_right\">NA</td>\n<td class=\"gt_row gt_right\">NA</td>\n<td class=\"gt_row gt_right\">NA</td></tr>\n    <tr><td class=\"gt_row gt_left\">October 1, 2021</td>\n<td class=\"gt_row gt_right\">19.890%</td>\n<td class=\"gt_row gt_right\">NA</td>\n<td class=\"gt_row gt_right\">NA</td>\n<td class=\"gt_row gt_right\">NA</td>\n<td class=\"gt_row gt_right\">NA</td>\n<td class=\"gt_row gt_right\">NA</td>\n<td class=\"gt_row gt_right\">NA</td></tr>\n    <tr><td class=\"gt_row gt_left\">November 1, 2021</td>\n<td class=\"gt_row gt_right\">21.313%</td>\n<td class=\"gt_row gt_right\">NA</td>\n<td class=\"gt_row gt_right\">NA</td>\n<td class=\"gt_row gt_right\">NA</td>\n<td class=\"gt_row gt_right\">NA</td>\n<td class=\"gt_row gt_right\">NA</td>\n<td class=\"gt_row gt_right\">NA</td></tr>\n    <tr><td class=\"gt_row gt_left\">December 1, 2021</td>\n<td class=\"gt_row gt_right\">36.081%</td>\n<td class=\"gt_row gt_right\">NA</td>\n<td class=\"gt_row gt_right\">NA</td>\n<td class=\"gt_row gt_right\">NA</td>\n<td class=\"gt_row gt_right\">NA</td>\n<td class=\"gt_row gt_right\">NA</td>\n<td class=\"gt_row gt_right\">NA</td></tr>\n    <tr><td class=\"gt_row gt_left\">January 1, 2022</td>\n<td class=\"gt_row gt_right\">48.691%</td>\n<td class=\"gt_row gt_right\">NA</td>\n<td class=\"gt_row gt_right\">NA</td>\n<td class=\"gt_row gt_right\">NA</td>\n<td class=\"gt_row gt_right\">NA</td>\n<td class=\"gt_row gt_right\">NA</td>\n<td class=\"gt_row gt_right\">NA</td></tr>\n    <tr><td class=\"gt_row gt_left\">February 1, 2022</td>\n<td class=\"gt_row gt_right\">54.439%</td>\n<td class=\"gt_row gt_right\">NA</td>\n<td class=\"gt_row gt_right\">NA</td>\n<td class=\"gt_row gt_right\">NA</td>\n<td class=\"gt_row gt_right\">NA</td>\n<td class=\"gt_row gt_right\">NA</td>\n<td class=\"gt_row gt_right\">NA</td></tr>\n    <tr><td class=\"gt_row gt_left\">March 1, 2022</td>\n<td class=\"gt_row gt_right\">61.145%</td>\n<td class=\"gt_row gt_right\">NA</td>\n<td class=\"gt_row gt_right\">NA</td>\n<td class=\"gt_row gt_right\">NA</td>\n<td class=\"gt_row gt_right\">NA</td>\n<td class=\"gt_row gt_right\">NA</td>\n<td class=\"gt_row gt_right\">NA</td></tr>\n    <tr><td class=\"gt_row gt_left\">April 1, 2022</td>\n<td class=\"gt_row gt_right\">69.971%</td>\n<td class=\"gt_row gt_right\">NA</td>\n<td class=\"gt_row gt_right\">NA</td>\n<td class=\"gt_row gt_right\">NA</td>\n<td class=\"gt_row gt_right\">NA</td>\n<td class=\"gt_row gt_right\">NA</td>\n<td class=\"gt_row gt_right\">NA</td></tr>\n    <tr><td class=\"gt_row gt_left\">May 1, 2022</td>\n<td class=\"gt_row gt_right\">73.496%</td>\n<td class=\"gt_row gt_right\">NA</td>\n<td class=\"gt_row gt_right\">NA</td>\n<td class=\"gt_row gt_right\">NA</td>\n<td class=\"gt_row gt_right\">NA</td>\n<td class=\"gt_row gt_right\">NA</td>\n<td class=\"gt_row gt_right\">NA</td></tr>\n    <tr><td class=\"gt_row gt_left\">June 1, 2022</td>\n<td class=\"gt_row gt_right\">78.618%</td>\n<td class=\"gt_row gt_right\">NA</td>\n<td class=\"gt_row gt_right\">NA</td>\n<td class=\"gt_row gt_right\">NA</td>\n<td class=\"gt_row gt_right\">NA</td>\n<td class=\"gt_row gt_right\">NA</td>\n<td class=\"gt_row gt_right\">NA</td></tr>\n    <tr><td class=\"gt_row gt_left\">July 1, 2022</td>\n<td class=\"gt_row gt_right\">NA</td>\n<td class=\"gt_row gt_right\">78.961%</td>\n<td class=\"gt_row gt_right\">80.716%</td>\n<td class=\"gt_row gt_right\">82.470%</td>\n<td class=\"gt_row gt_right\">84.225%</td>\n<td class=\"gt_row gt_right\">85.979%</td>\n<td class=\"gt_row gt_right\">87.734%</td></tr>\n    <tr><td class=\"gt_row gt_left\">August 1, 2022</td>\n<td class=\"gt_row gt_right\">NA</td>\n<td class=\"gt_row gt_right\">80.519%</td>\n<td class=\"gt_row gt_right\">84.076%</td>\n<td class=\"gt_row gt_right\">87.668%</td>\n<td class=\"gt_row gt_right\">91.294%</td>\n<td class=\"gt_row gt_right\">94.955%</td>\n<td class=\"gt_row gt_right\">98.651%</td></tr>\n    <tr><td class=\"gt_row gt_left\">September 1, 2022</td>\n<td class=\"gt_row gt_right\">NA</td>\n<td class=\"gt_row gt_right\">81.852%</td>\n<td class=\"gt_row gt_right\">87.253%</td>\n<td class=\"gt_row gt_right\">92.760%</td>\n<td class=\"gt_row gt_right\">98.374%</td>\n<td class=\"gt_row gt_right\">104.096%</td>\n<td class=\"gt_row gt_right\">109.927%</td></tr>\n    <tr><td class=\"gt_row gt_left\">October 1, 2022</td>\n<td class=\"gt_row gt_right\">NA</td>\n<td class=\"gt_row gt_right\">81.153%</td>\n<td class=\"gt_row gt_right\">88.362%</td>\n<td class=\"gt_row gt_right\">95.784%</td>\n<td class=\"gt_row gt_right\">103.423%</td>\n<td class=\"gt_row gt_right\">111.284%</td>\n<td class=\"gt_row gt_right\">119.371%</td></tr>\n    <tr><td class=\"gt_row gt_left\">November 1, 2022</td>\n<td class=\"gt_row gt_right\">NA</td>\n<td class=\"gt_row gt_right\">78.507%</td>\n<td class=\"gt_row gt_right\">87.430%</td>\n<td class=\"gt_row gt_right\">96.707%</td>\n<td class=\"gt_row gt_right\">106.348%</td>\n<td class=\"gt_row gt_right\">116.363%</td>\n<td class=\"gt_row gt_right\">126.763%</td></tr>\n    <tr><td class=\"gt_row gt_left\">December 1, 2022</td>\n<td class=\"gt_row gt_right\">NA</td>\n<td class=\"gt_row gt_right\">60.314%</td>\n<td class=\"gt_row gt_right\">69.978%</td>\n<td class=\"gt_row gt_right\">80.123%</td>\n<td class=\"gt_row gt_right\">90.768%</td>\n<td class=\"gt_row gt_right\">101.932%</td>\n<td class=\"gt_row gt_right\">113.635%</td></tr>\n    <tr><td class=\"gt_row gt_left\">January 1, 2023</td>\n<td class=\"gt_row gt_right\">NA</td>\n<td class=\"gt_row gt_right\">47.177%</td>\n<td class=\"gt_row gt_right\">57.579%</td>\n<td class=\"gt_row gt_right\">68.606%</td>\n<td class=\"gt_row gt_right\">80.287%</td>\n<td class=\"gt_row gt_right\">92.655%</td>\n<td class=\"gt_row gt_right\">105.743%</td></tr>\n    <tr><td class=\"gt_row gt_left\">February 1, 2023</td>\n<td class=\"gt_row gt_right\">NA</td>\n<td class=\"gt_row gt_right\">43.233%</td>\n<td class=\"gt_row gt_right\">54.860%</td>\n<td class=\"gt_row gt_right\">67.305%</td>\n<td class=\"gt_row gt_right\">80.616%</td>\n<td class=\"gt_row gt_right\">94.845%</td>\n<td class=\"gt_row gt_right\">110.045%</td></tr>\n    <tr><td class=\"gt_row gt_left\">March 1, 2023</td>\n<td class=\"gt_row gt_right\">NA</td>\n<td class=\"gt_row gt_right\">38.528%</td>\n<td class=\"gt_row gt_right\">51.242%</td>\n<td class=\"gt_row gt_right\">64.982%</td>\n<td class=\"gt_row gt_right\">79.821%</td>\n<td class=\"gt_row gt_right\">95.835%</td>\n<td class=\"gt_row gt_right\">113.104%</td></tr>\n    <tr><td class=\"gt_row gt_left\">April 1, 2023</td>\n<td class=\"gt_row gt_right\">NA</td>\n<td class=\"gt_row gt_right\">31.749%</td>\n<td class=\"gt_row gt_right\">45.251%</td>\n<td class=\"gt_row gt_right\">59.985%</td>\n<td class=\"gt_row gt_right\">76.051%</td>\n<td class=\"gt_row gt_right\">93.555%</td>\n<td class=\"gt_row gt_right\">112.610%</td></tr>\n    <tr><td class=\"gt_row gt_left\">May 1, 2023</td>\n<td class=\"gt_row gt_right\">NA</td>\n<td class=\"gt_row gt_right\">30.495%</td>\n<td class=\"gt_row gt_right\">45.278%</td>\n<td class=\"gt_row gt_right\">61.569%</td>\n<td class=\"gt_row gt_right\">79.503%</td>\n<td class=\"gt_row gt_right\">99.230%</td>\n<td class=\"gt_row gt_right\">120.908%</td></tr>\n    <tr><td class=\"gt_row gt_left\">June 1, 2023</td>\n<td class=\"gt_row gt_right\">NA</td>\n<td class=\"gt_row gt_right\">26.824%</td>\n<td class=\"gt_row gt_right\">42.576%</td>\n<td class=\"gt_row gt_right\">60.103%</td>\n<td class=\"gt_row gt_right\">79.586%</td>\n<td class=\"gt_row gt_right\">101.220%</td>\n<td class=\"gt_row gt_right\">125.219%</td></tr>\n    <tr><td class=\"gt_row gt_left\">July 1, 2023</td>\n<td class=\"gt_row gt_right\">NA</td>\n<td class=\"gt_row gt_right\">26.824%</td>\n<td class=\"gt_row gt_right\">42.576%</td>\n<td class=\"gt_row gt_right\">60.103%</td>\n<td class=\"gt_row gt_right\">79.586%</td>\n<td class=\"gt_row gt_right\">101.220%</td>\n<td class=\"gt_row gt_right\">125.219%</td></tr>\n    <tr><td class=\"gt_row gt_left\">August 1, 2023</td>\n<td class=\"gt_row gt_right\">NA</td>\n<td class=\"gt_row gt_right\">26.824%</td>\n<td class=\"gt_row gt_right\">42.576%</td>\n<td class=\"gt_row gt_right\">60.103%</td>\n<td class=\"gt_row gt_right\">79.586%</td>\n<td class=\"gt_row gt_right\">101.220%</td>\n<td class=\"gt_row gt_right\">125.219%</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\nBaz etkisi sayesinde yıllık enflasyonun 2022 yılının Aralık ayı ve Ocak 2023'te bir miktar düşeceği görülmektedir. Ancak bu düşüş aslında 2021 Aralık ve 2022 Ocak'ta açıklanan yüksek oranların hesaplama penceresini terk etmesi kaynaklıdır.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(Estimates[Estimates$Tarih>my(\"January 2021\"),],aes(x=Tarih))+\n  geom_line(aes(y=Yıl, color=\"Geçmiş Oranlar\"),size=1.5,na.rm=TRUE)+\n  geom_line(aes(y=Yıl2, color=\"Aylık %2 Varsayımı\"),size=0.9,na.rm=TRUE)+\n  geom_line(aes(y=Yıl3, color=\"Aylık %3 Varsayımı\"),size=0.9,na.rm=TRUE)+\n  geom_line(aes(y=Yıl4, color=\"Aylık %4 Varsayımı\"),size=1.2,na.rm=TRUE)+\n  geom_line(aes(y=Yıl5, color=\"Aylık %5 Varsayımı\"),size=1.2,na.rm=TRUE)+\n  geom_line(aes(y=Yıl6, color=\"Aylık %6 Varsayımı\"),size=1.2,na.rm=TRUE)+\n  geom_line(aes(y=Yıl7, color=\"Aylık %7 Varsayımı\"),size=1.2,na.rm=TRUE)+\n  scale_y_continuous(labels = scales::percent)+\n  labs(x=\"Tarih\", y=\"Yıllık Enflasyon\")+\n  theme(legend.title = element_blank(),legend.position = \"top\")+\n  (scale_x_date(breaks=date_breaks(\"2 months\"),\n      labels=date_format(\"%m %Y\")))+\n  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))\n```\n\n::: {.cell-output-display}\n![](enflasyon_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n## Üniversite Analitiğine Etkileri\n\n2022 yılının ortaları ekonomik krizin etkilerinin iyice hissedildiği bir dönem olarak hatırlanacak. Vakıf üniversiteleri bu volatil ortamda ücret politikalarını belirlerken oldukça zorlandı. Eğitim ücretlerine %30-%110 aralığında zamlar yapıldı. Enflasyonla doğrudan ilişkili maliyet artışına, asgari ücrete yıl içinde yapılan zam, akademik personele yılda iki defa zamlanan devletin emsal ücretini ödeme gibi kanun maddelerinin getirdiği yükler bütçeleri zorladı.    \n\nEnflasyon tahmninin üniversite analitiğine tam da bu aşamada faydası bulunmaktadır. Aylık artış oranları senaryoları için takip eden akdemik dönem boyunca etken olacak **ortalama enflasyon** oranı ile eğitim ücretlerine yapılacak zam oranı için bir alt sınır tespit edilebilir. Aşağıda  bu hesaplama sonucu elde edilen değerler göre Aylık ortalama %5 enflasyon senaryosu ile Eylül 2022 - Ağustos 2023 döneminde Yıllık Enflasyon ortalama %86.2 seviyelerinde olacak. Aylık beklenti %4 olduğunda bu değer %72.3'e düşerken, %6 olduğunda ise %101 seviyesine çıkmaktadır.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmeanN <- function(x){\n  mean(x,na.rm = TRUE)\n}\nortenf <- apply(Estimates[225:236,11:16], 2, meanN)\nortenf\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n     Yıl2      Yıl3      Yıl4      Yıl5      Yıl6      Yıl7 \n0.4778998 0.5958017 0.7234427 0.8616246 1.0112120 1.1731369 \n```\n:::\n:::\n",
    "supporting": [
      "enflasyon_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}