---
title: "yksBaraj"
author: "RSA"
description: "This is Part 1 of a series of blog posts on how to understand regression. The goal is to develop an intuitive understanding of the different components of regression. In this first post, we figure out where the estimate of an intercept-only regression model comes from."
date: 2020-08-01
categories:
  - statistics
  - tutorial
  - regression
code-fold: true
toc: true
toc-location: body
---

## The Black Box of Regression

Statistical regression techniques are an important concept in data analysis. As a social scientist, I use it to test hypotheses by comparing differences between groups or testing relationships between variables. While it is easy to run regression analyses in a variety of software packages, like SPSS or R, it often remains a black box that is not well understood. I, in fact, do not believe I actually understand regression. Not fully understanding the mechanics of regression could be okay, though. After all, you also don't need to know exactly how car engines work in order to drive a car. However, I think many users of regression have isolated themselves too much from the mechanics of regression. This may be the source of some errors, such as applying regression to data that is not suitable for the regression method. If you're using regression to try and make inferences about the world, it's probably also a good idea to feel like you know what you're doing.

So, there are some reasons to figure out regression. This post is Part 1 of a series of blog posts called 'Understanding Regression' in which I try to figure it out.

Feel free to follow me along by copy-pasting the code from each step. I'll add a note in case you need to slightly adjust the code for it to work on your computer.

## Setup

To figure out regression, we need data. We could make up some data on the spot, but I'd rather use data that is a bit more meaningful (to me, anyway). Since I'm a big Pokémon fan, I'll use a data set containing Pokémon statistics.

In case you're following along, start by loading some packages and reading in the [data](https://www.willemsleegers.com/data/pokemon.csv). In the code section below I use the `here` package to read in the data, but I recommend that you simply specify the path to the file. After that, I subset the data to make the data a bit more manageable and define a custom `mode` function because R does not have one (and I need it later).
