<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="tr" xml:lang="tr"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-0.9.368">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Raif Serkan Albayrak">
<meta name="description" content="Soru gruplarının puan hesaplanmasında katsayıları nedir? YKS çoğunlukla sıralamalaarla ilgili olsa da analizlerin bir noktasında puanlarla ilgili bilgiye başvurulabiliyor. Örneğin bir bölüme yerleşen ortalama öğrenci bilgisi ATLAS’da netler üzerinden veriliyor. Bu bilgi bölüme yerleşen öğrencilerin sıralama dağılımlarının belirlenmesinde, farklı kontenjan (indirim) tiplerinden öğrenci alan bölümlere yerleşen ortalama öğrencinin belirlenmesinde ve bu sayede de bölüm bazında üniversite sıralamasında kullanılıyor.">

<title>Zeytin - YKS Puanı Hesaplama Formülleri</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<meta name="quarto:offset" content="../../../">
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<link href="../../../images/olive_fav.png" rel="icon" type="image/png">
<script src="../../../site_libs/quarto-html/quarto.js"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link id="quarto-text-highlighting-styles" href="../../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "Sonuç yok",
    "search-matching-documents-text": "eşleşen belgeler",
    "search-copy-link-title": "Aramak için bağlantıyı kopyalayın",
    "search-hide-matches-text": "Ek eşleşmeleri gizle",
    "search-more-match-text": "bu belgede daha fazla eşleşme",
    "search-more-matches-text": "bu belgede daha fazla eşleşmeler",
    "search-clear-button-title": "Temizle",
    "search-detached-cancel-button-title": "İptal et",
    "search-submit-button-title": "Göndermek"
  }
}</script>
<script src="..\..\..\site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="..\..\..\site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="../../../styles.css">
</head>

<body class="floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <a class="navbar-brand" href="../../../index.html">
    <span class="navbar-title">Zeytin</span>
  </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../../index.html">Ana Sayfa</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../about.html">İletişim</a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto">
    <nav id="TOC" role="doc-toc">
    <h2 id="toc-title">İçerik</h2>
   
  <ul>
  <li><a href="#veri" id="toc-veri" class="nav-link active" data-scroll-target="#veri">Veri</a>
  <ul class="collapse">
  <li><a href="#tyt-puanı" id="toc-tyt-puanı" class="nav-link" data-scroll-target="#tyt-puanı">TYT Puanı</a>
  <ul class="collapse">
  <li><a href="#hata-analizi" id="toc-hata-analizi" class="nav-link" data-scroll-target="#hata-analizi">Hata Analizi</a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
    </div>
<!-- main -->
<main class="content column-page-right" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">YKS Puanı Hesaplama Formülleri</h1>
  <div class="quarto-categories">
    <div class="quarto-category">YKS</div>
    <div class="quarto-category">Modelleme</div>
    <div class="quarto-category">R</div>
  </div>
  </div>

<div>
  <div class="description">
    Soru gruplarının puan hesaplanmasında katsayıları nedir? YKS çoğunlukla sıralamalaarla ilgili olsa da analizlerin bir noktasında puanlarla ilgili bilgiye başvurulabiliyor. Örneğin bir bölüme yerleşen ortalama öğrenci bilgisi ATLAS’da netler üzerinden veriliyor. Bu bilgi bölüme yerleşen öğrencilerin sıralama dağılımlarının belirlenmesinde, farklı kontenjan (indirim) tiplerinden öğrenci alan bölümlere yerleşen ortalama öğrencinin belirlenmesinde ve bu sayede de bölüm bazında üniversite sıralamasında kullanılıyor.
  </div>
</div>




<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Yazar</div>
    <div class="quarto-title-meta-contents">
             <p>Raif Serkan Albayrak </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Yayınlanma Tarihi</div>
    <div class="quarto-title-meta-contents">
      <p class="date">31 Mayıs 2022</p>
    </div>
  </div>
    
  </div>
  

</header>

<section id="veri" class="level1">
<h1>Veri</h1>
<p>Her puan türü<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> için soru gruplarının çarpan değerini hesaplayabilmek için ATLAS’da yayınlanan <a href="https://yokatlas.yok.gov.tr/netler-tablo.php?b=19001">TYT-AYT Net Sihirbazında</a> bulunan veriden faydalanılmıştır. Önlisans verisine de adreste <a href="https://yokatlas.yok.gov.tr/netler-onlisans-tablo.php?b=30001">ufak bir değişiklikle</a> ulaşılmaktadır. Dikkat edilirse sayfada seçilen bölüm için kontenjan bazında son yerleşen öğrencinin netleri ve orta-öğretim başarı puanı (OBP) verilmekte ancak bu öğrencinin puanı verilmemektedir. Aslında sayfada bu bilgi de mevcuttur<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a> fakat ATLAS bu bilgiyi göstermemeyi tercih etmektedir. En güncel veri üzerinden çalışıldı ancak istenirse 2020 ve daha eski veriye de ulaşmak mümkündür<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a>. Bu sayfada bulunan tüm lisans ve önlisans bölüm isimlerine gene sayfanın kodu içinden ulaşmak mümkündür. Bölüm isimlerinin bulunduğu dosya <a href="https://github.com/SerkanAlbayrak/d3/raw/master/content/posts/05_2022_yks_puan%20hesaplama/kodlar.xlsx">buradan</a> indirilebilir.</p>
<div class="cell">
<details>
<summary>Kod</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>kodlar <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"kodlar.xlsx"</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>kodlar</span></code><button title="Panoya Kopyala" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 745 × 4
      id bölüm                                        tip   PuanTuru
   &lt;dbl&gt; &lt;chr&gt;                                        &lt;chr&gt; &lt;chr&gt;   
 1 19001 ACİL YARDIM VE AFET YÖNETİMİ (FAKÜLTE)       AYT   SAY     
 2 20001 ACİL YARDIM VE AFET YÖNETİMİ (YÜKSEKOKUL)    AYT   SAY     
 3 19502 ADLİ BİLİMLER                                AYT   SAY     
 4 19002 ADLİ BİLİŞİM MÜHENDİSLİĞİ                    AYT   SAY     
 5 39001 ADLİ BİLİŞİM MÜHENDİSLİĞİ (M.T.O.K.)         AYT   SAY     
 6 19003 AĞAÇ İŞLERİ ENDÜSTRİ MÜHENDİSLİĞİ            AYT   SAY     
 7 50005 AĞAÇ İŞLERİ ENDÜSTRİ MÜHENDİSLİĞİ (M.T.O.K.) AYT   SAY     
 8 10001 AİLE VE TÜKETİCİ BİLİMLERİ                   AYT   EA      
 9 18002 AKTÜERYA BİLİMLERİ (FAKÜLTE)                 AYT   SAY     
10 20004 AKTÜERYA BİLİMLERİ (YÜKSEKOKUL)              AYT   SAY     
# … with 735 more rows</code></pre>
</div>
</div>
<p>Verinin ilk 480 satırı lisans gerisi onlisans bölümlerden oluşmakta. Her bölüm için adres çubuğundaki bölüm kodu değiştirilerek o bölümle ilgili tüm kontenjanlarda bulunan detaylara ulaşmak mümkündür. Basit bir döngü ve veri üzerinde her zamanki kadar zahmetli olan düzenlemeleri yaparak parametrelerin tahmininde kullanılan veri hazırlanmış olur. Ek olarak puanlar hesaplanırken OBP katsayısının cezalı kullanılıp kullanılmadığını anlamak amacıyla her programın detay sayfasından yerleşen son öğrencinin Öğrenim durumu bilgisi de çekilip veriye eklenmiştir. Verinin hazır formu <a href="https://github.com/SerkanAlbayrak/d3/raw/master/content/posts/05_2022_yks_puan%20hesaplama/puanData.xlsx">buradan</a> indirilebilir.</p>
<div class="cell">
<details>
<summary>Kod</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>all <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"puanData.xlsx"</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>all<span class="sc">$</span>PuanTuru <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(all<span class="sc">$</span><span class="st">`</span><span class="at">PuanTuru</span><span class="st">`</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>all</span></code><button title="Panoya Kopyala" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 20,069 × 28
   ProgramKodu Üniversite      Yılı Türü  Katsayı   OBP  Puan Yerl. `TYT Türkçe`
         &lt;dbl&gt; &lt;chr&gt;          &lt;dbl&gt; &lt;chr&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;        &lt;dbl&gt;
 1   101290082 ARDAHAN ÜNİV.…  2021 Devl…    0.12  363.  246.     2         22.5
 2   101890037 BAYBURT ÜNİV.…  2021 Devl…    0.12  361.  240.     1         15.5
 3   102710387 ÇANAKKALE ONS…  2021 Devl…    0.12  429.  238.    62         23.8
 4   111091394 SAĞLIK BİLİML…  2021 Devl…    0.12  398.  235.    41         19.5
 5   104710336 GÜMÜŞHANE ÜNİ…  2021 Devl…    0.12  371.  227.     1         14  
 6   108990307 SELÇUK ÜNİV. …  2021 Devl…    0.12  366.  225.    62         10.2
 7   101370270 ARTVİN ÇORUH …  2021 Devl…    0.12  327.  220.     7         16.5
 8   109590048 MUNZUR ÜNİV. …  2021 Devl…    0.12  413.  218.    11         13.5
 9   107710442 HATAY MUSTAFA…  2021 Devl…    0.12  462.  214.    52         NA  
10   100890057 AKSARAY ÜNİV.…  2021 Devl…    0.12  417.  210.    25         12.5
# … with 20,059 more rows, and 19 more variables: `TYT Sosyal` &lt;dbl&gt;,
#   `TYT Mat` &lt;dbl&gt;, `TYT Fen` &lt;dbl&gt;, `AYT Mat` &lt;dbl&gt;, `AYT Fizik` &lt;dbl&gt;,
#   `AYT Kimya` &lt;dbl&gt;, `AYT Biyoloji` &lt;dbl&gt;, `AYT Türkçe` &lt;chr&gt;,
#   `AYT Tarih1` &lt;chr&gt;, `AYT Coğrafya1` &lt;chr&gt;, `AYT TDE` &lt;chr&gt;,
#   `AYT Tar2` &lt;chr&gt;, `AYT Coğ2` &lt;chr&gt;, `AYT Fel` &lt;chr&gt;, `AYT Din` &lt;chr&gt;,
#   `YDT Dil` &lt;chr&gt;, PuanTuru &lt;fct&gt;, BoluMKodu &lt;dbl&gt;, stuType &lt;chr&gt;</code></pre>
</div>
</div>
<section id="tyt-puanı" class="level2">
<h2 class="anchored" data-anchor-id="tyt-puanı">TYT Puanı</h2>
<p><a href="../05_2022_yks_puan_diagram/yks_puan_diagram.html">YKS puanlama sisteminin</a> anlatıldığı daha önceki bir yazıda aşağıdaki diagram kullanılmıştı. Buna göre TYT Sınav puanı Temel Matematik, Türkçe, Fen Bilimleri ve Sosyal Bilimleri soru gruplarından toplanan puanlardan oluşur. Her soru grubunun etkisi farklıdır. Bazı soru gruplarından yapılan netler sonuçta hesaplanan puanı diğerlerinden daha fazla etkiler. İşte amaç soru gruplarının bu etkilerini tahmin etmektir. Bu amaçla basit bir regresyon modeli kurulmuştur.</p>
<div id="fig-puandiagram" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="puandiagram.png" class="img-fluid figure-img"></p>
<p></p><figcaption aria-hidden="true" class="figure-caption">Figür 1: Puan Diagramı</figcaption><p></p>
</figure>
</div>
<p>Regresyon modeli<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a> ile soru gruplarının sonuç puan üzerindeki etkisini gösteren <strong>katsayılar</strong> hesaplanacaktır. Modelin yapısı şu şekilde gösterilebilir: $$ TYTPuan=c+_1 TemelMatematik+_2 Türkçe+_3 FenBilimleri+_4 SosyalBilimler+</p>
<p>$$ Katsayılar hesaplanmadan önce verideki yerleştirme puanlarından OBP etkisinin ayıklanması gerekmekte. OBP etkisi öğrencinin mezun olduğu lise ile yerleştiği program arasında bir bağlantı olmasına göre 0.18 ile 0.12 değerlerinden birini alıyor.</p>
<p>$$</p>
<p>TYT_{Sınav} = TYT_{Yerleştirme}-(0.12: veya: 0.18)OBP</p>
<p>$$</p>
<div class="cell">
<details>
<summary>Kod</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>all<span class="sc">$</span>SinavPuan <span class="ot">&lt;-</span> all<span class="sc">$</span>Puan<span class="sc">-</span>all<span class="sc">$</span>Katsayı<span class="sc">*</span>all<span class="sc">$</span>OBP</span></code><button title="Panoya Kopyala" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Regresyon modelinin katsayılarının hesaplanacağı veride modellemeye başlamadan önce yapılması gereken detay gibi görünen ama oldukça kritik bir filtreleme gerekmektedir. Eğer bir öğrenci YKS sınavında bir programa yerleşirse bir sonraki yıl OBP katsayısı yarı yarıya kesiliyor. Diğer bir deyişle YKS Yerleşme Puanını hesaplamak için, normalde OBP puanı 0.12 (veya 0.18) ile çarpılıp YKS sınav sonuç puan ekleneceğine 0.06 (veya 0.09) ile çarpılıp eklenmektedir. Dolayısıyla regresyon katsayılarının hesaplanacağı veride bu gibi durumların filtrelenmesi gerekmekte. Ne var ki, YÖK ATLAS bu konuda net bilgi içermemekte. Aşağıdaki grafikte <span class="math inline">\(TYT_{Sınav}\)</span> hesaplandıktan sonra yerleştirme ve sınav puanlarının çapraz grafiği gösterilmektedir. Açık renkli bölgeler 150 puanın altında kalan sınav puanlarını göstermektedir. Bu puanlar mümkün olmadığına göre, bu programa son yerleşen adayların OBP katsayıları cezalı hesaplanmış olmalıdır.</p>
<div class="cell" data-warnings="false">
<details>
<summary>Kod</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb6-2"><a href="#cb6-2"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb6-3"><a href="#cb6-3"></a>all<span class="sc">$</span>l50 <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(all<span class="sc">$</span>SinavPuan<span class="sc">&lt;</span><span class="dv">150</span>,<span class="dv">150</span><span class="sc">-</span>all<span class="sc">$</span>SinavPuan,<span class="dv">0</span>)</span>
<span id="cb6-4"><a href="#cb6-4"></a><span class="fu">ggplot</span>(all, <span class="fu">aes</span>(<span class="at">x=</span>Puan, <span class="at">y=</span>SinavPuan, <span class="at">colour=</span>l50))<span class="sc">+</span><span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb6-5"><a href="#cb6-5"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"TYT Puanı Modelinde Hata Terimleri"</span>,</span>
<span id="cb6-6"><a href="#cb6-6"></a>       <span class="at">x =</span> <span class="st">"Yerleşme Puanı"</span>,</span>
<span id="cb6-7"><a href="#cb6-7"></a>       <span class="at">y =</span> <span class="st">"Sınav Puanı"</span>,</span>
<span id="cb6-8"><a href="#cb6-8"></a>       <span class="at">colour=</span> <span class="st">"Hata"</span>) <span class="sc">+</span> </span>
<span id="cb6-9"><a href="#cb6-9"></a>  <span class="fu">geom_abline</span>(<span class="at">slope =</span> <span class="dv">0</span>, <span class="at">intercept =</span> <span class="dv">0</span>, <span class="at">colour=</span><span class="st">"orange"</span>, <span class="at">size=</span><span class="dv">1</span>)</span></code><button title="Panoya Kopyala" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="puan_hesaplama_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Mesela yukarıdaki grafikte 150 puan altında sınav puanlarına sahip öğrencilerin yerleştiği görünen programlara son sırada yerleşen öğrencilerin bilgilerine program detay sayfalarından da ulaşıldığında öğrencinin <strong>Öğrenim Durumu</strong> bilgisi aşağıdaki tablodaki gibi çıkıyor.</p>
<div class="cell" data-warnings="false">
<details>
<summary>Kod</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1"></a><span class="fu">library</span>(kableExtra)</span>
<span id="cb7-2"><a href="#cb7-2"></a><span class="fu">table</span>(all<span class="sc">$</span>stuType[all<span class="sc">$</span>l50<span class="sc">&gt;</span><span class="dv">0</span>]) <span class="sc">|&gt;</span> <span class="fu">kbl</span>(<span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Yerleşen Öğrencinin Öğrenim Durumu"</span>, <span class="st">"Frekans"</span>))</span></code><button title="Panoya Kopyala" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table>
 <thead>
  <tr>
   <th style="text-align:left;"> Yerleşen Öğrencinin Öğrenim Durumu </th>
   <th style="text-align:right;"> Frekans </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> Bir üniversiteden daha önce mezun olmuş </td>
   <td style="text-align:right;"> 48 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Daha önce yerleşip kayıt yaptırmamış ya da kaydı silinmiş </td>
   <td style="text-align:right;"> 425 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Lise mezunu, daha önce hiç üniversiteye yerleşmemişti. </td>
   <td style="text-align:right;"> 234 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Üniversitede öğrenci iken sınava girip buraya yerleşti </td>
   <td style="text-align:right;"> 876 </td>
  </tr>
</tbody>
</table>

</div>
</div>
<p>Ancak verideki tüm programlar için bu tablo oluşturulduğunda, sadece <strong>Liseden yeni mezun ÖSYSye ilk girişinde yerleşti</strong> değerinin yukarıdaki tablodan farklı olduğu net görülüyor. Dolayısıyla bu öğrencilerin hiçbiri için OBP’nin cezalı hesaplanmadığı anlaşılmaktadır. Her ne kadar bu duum aslında daha en baştan açık görünse de aynı mantıkla <strong>Lise mezunu, daha önce hiç üniversiteye yerleşmemişti</strong> öğrenim durumuna sahip bir öğrencinin de OBP katsayısının cezalı hesaplanmaması beklenirdi. Ancak yukarıdaki tabloya göre en az 234 adet böyle durum var.</p>
<div class="cell">
<details>
<summary>Kod</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(all<span class="sc">$</span>stuType) <span class="sc">|&gt;</span> <span class="fu">kbl</span>(<span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Yerleşen Öğrencinin Öğrenim Durumu"</span>, <span class="st">"Frekans"</span>))</span></code><button title="Panoya Kopyala" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table>
 <thead>
  <tr>
   <th style="text-align:left;"> Yerleşen Öğrencinin Öğrenim Durumu </th>
   <th style="text-align:right;"> Frekans </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> Bir üniversiteden daha önce mezun olmuş </td>
   <td style="text-align:right;"> 1329 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Daha önce yerleşip kayıt yaptırmamış ya da kaydı silinmiş </td>
   <td style="text-align:right;"> 1122 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Lise mezunu, daha önce hiç üniversiteye yerleşmemişti. </td>
   <td style="text-align:right;"> 8948 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Liseden yeni mezun ÖSYSye ilk girişinde yerleşti </td>
   <td style="text-align:right;"> 5592 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Üniversitede öğrenci iken sınava girip buraya yerleşti </td>
   <td style="text-align:right;"> 3078 </td>
  </tr>
</tbody>
</table>

</div>
</div>
<p>OBP’nin puan üzerindeki etkisini kontrol altına alabilmek amacıyla verinin sadece <strong>Liseden yeni mezun ÖSYSye ilk girişinde yerleşti</strong> öğrenim durumuna sahip kısmı filtreleniyor.</p>
<div class="cell">
<details>
<summary>Kod</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>modeldata <span class="ot">&lt;-</span> all[all<span class="sc">$</span>stuType<span class="sc">==</span><span class="st">"Liseden yeni mezun ÖSYSye ilk girişinde yerleşti"</span>,]</span></code><button title="Panoya Kopyala" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Veriyi modele beslemeden önce son olarak TYT puanı ile yerleşim yapılan bölümler filtreleniyor.</p>
<div class="cell">
<details>
<summary>Kod</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>modeldataTYT <span class="ot">&lt;-</span> modeldata[modeldata<span class="sc">$</span>PuanTuru<span class="sc">==</span><span class="st">"TYT"</span>,]</span></code><button title="Panoya Kopyala" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Verinin TYT ile yerleştirme yapılan kısmı filtrelenerek katsayılar aşağıda kurulan model ile tahminleniyor. Model veriyi %99.9 oranda başarıyla açıklıyor.</p>
<div class="cell" data-warnings="false">
<details>
<summary>Kod</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1"></a><span class="fu">library</span>(jtools)</span>
<span id="cb11-2"><a href="#cb11-2"></a>TYTModel <span class="ot">&lt;-</span> <span class="fu">lm</span>(SinavPuan<span class="sc">~</span><span class="st">`</span><span class="at">TYT Mat</span><span class="st">`</span><span class="sc">+</span><span class="st">`</span><span class="at">TYT Türkçe</span><span class="st">`</span><span class="sc">+</span><span class="st">`</span><span class="at">TYT Fen</span><span class="st">`</span><span class="sc">+</span><span class="st">`</span><span class="at">TYT Sosyal</span><span class="st">`</span>, <span class="at">data=</span>modeldataTYT)</span>
<span id="cb11-3"><a href="#cb11-3"></a></span>
<span id="cb11-4"><a href="#cb11-4"></a><span class="fu">summ</span>(TYTModel,<span class="at">digits =</span> <span class="dv">5</span>)</span></code><button title="Panoya Kopyala" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="table table-striped table-hover table-condensed table-responsive" style="width: auto !important; margin-left: auto; margin-right: auto;">
<tbody>
  <tr>
   <td style="text-align:left;font-weight: bold;"> Observations </td>
   <td style="text-align:right;"> 2320 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> Dependent variable </td>
   <td style="text-align:right;"> SinavPuan </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> Type </td>
   <td style="text-align:right;"> OLS linear regression </td>
  </tr>
</tbody>
</table> <table class="table table-striped table-hover table-condensed table-responsive" style="width: auto !important; margin-left: auto; margin-right: auto;">
<tbody>
  <tr>
   <td style="text-align:left;font-weight: bold;"> F(4,2315) </td>
   <td style="text-align:right;"> 3063149.52204 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> R² </td>
   <td style="text-align:right;"> 0.99981 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> Adj. R² </td>
   <td style="text-align:right;"> 0.99981 </td>
  </tr>
</tbody>
</table> <table class="table table-striped table-hover table-condensed table-responsive" style="width: auto !important; margin-left: auto; margin-right: auto;border-bottom: 0;">
 <thead>
  <tr>
   <th style="text-align:left;">   </th>
   <th style="text-align:right;"> Est. </th>
   <th style="text-align:right;"> S.E. </th>
   <th style="text-align:right;"> t val. </th>
   <th style="text-align:right;"> p </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;font-weight: bold;"> (Intercept) </td>
   <td style="text-align:right;"> 97.30995 </td>
   <td style="text-align:right;"> 0.02600 </td>
   <td style="text-align:right;"> 3742.64952 </td>
   <td style="text-align:right;"> 0.00000 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> `TYT Mat` </td>
   <td style="text-align:right;"> 4.52820 </td>
   <td style="text-align:right;"> 0.00303 </td>
   <td style="text-align:right;"> 1494.56400 </td>
   <td style="text-align:right;"> 0.00000 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> `TYT Türkçe` </td>
   <td style="text-align:right;"> 2.92197 </td>
   <td style="text-align:right;"> 0.00147 </td>
   <td style="text-align:right;"> 1985.94936 </td>
   <td style="text-align:right;"> 0.00000 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> `TYT Fen` </td>
   <td style="text-align:right;"> 3.18509 </td>
   <td style="text-align:right;"> 0.00400 </td>
   <td style="text-align:right;"> 796.57918 </td>
   <td style="text-align:right;"> 0.00000 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> `TYT Sosyal` </td>
   <td style="text-align:right;"> 2.98252 </td>
   <td style="text-align:right;"> 0.00263 </td>
   <td style="text-align:right;"> 1135.15370 </td>
   <td style="text-align:right;"> 0.00000 </td>
  </tr>
</tbody>
<tfoot><tr><td style="padding: 0; " colspan="100%">
<sup></sup> Standard errors: OLS</td></tr></tfoot>
</table>
</div>
<details>
<summary>Kod</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1"></a><span class="fu">plot_summs</span>(TYTModel)</span></code><button title="Panoya Kopyala" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="puan_hesaplama_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<section id="hata-analizi" class="level3">
<h3 class="anchored" data-anchor-id="hata-analizi">Hata Analizi</h3>
<p>Her istatistiki model hata içerir ve bu hataların incelenmesi sonucu genellikle modelin iyileşmesine yönelik adımlar atılır. Burada hata ile kastedilen modelin tahmini ile gerçek puan arasındaki farklılıktır. Aşağıdaki garfikte iki gözlemdeki hatanın büyüklüğü dikkat çekmektedir.</p>
<div class="cell">
<details>
<summary>Kod</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>results <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">real =</span> modeldataTYT<span class="sc">$</span>SinavPuan,<span class="at">model=</span><span class="fu">predict</span>(TYTModel))</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>results<span class="sc">$</span>fark <span class="ot">&lt;-</span> results<span class="sc">$</span>real<span class="sc">-</span>results<span class="sc">$</span>model</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>results<span class="sc">$</span>absfark <span class="ot">&lt;-</span> <span class="fu">abs</span>(results<span class="sc">$</span>real<span class="sc">-</span>results<span class="sc">$</span>model)</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(results, <span class="fu">aes</span>(<span class="at">x=</span>real, <span class="at">y=</span>fark, <span class="at">colour=</span>absfark))<span class="sc">+</span><span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"TYT Puanı Modelinde Hata Terimleri"</span>,</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Gözlem"</span>,</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Gözlem - Model"</span>,</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">colour=</span> <span class="st">"Hata"</span>) <span class="sc">+</span> </span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">slope =</span> <span class="dv">0</span>, <span class="at">intercept =</span> <span class="dv">0</span>, <span class="at">colour=</span><span class="st">"orange"</span>, <span class="at">size=</span><span class="dv">1</span>)</span></code><button title="Panoya Kopyala" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="puan_hesaplama_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Hataların ekstrem olduğu bu gözlemler çekildiğinde Üsküdar Üniversitesi Çocuk Gelişimi Burslu kontenjanına yerleşen öğrencini ve Avrasya Üniversitesi Diş Protez Teknolojisi Burslu programına yerleşen öğrencilerin puanları olması gerekenden 7.45 ve 16.67 puan daha <strong>fazla</strong> hesaplanmış görünüyor. Umarız buradaki maddi hata ATLAS veri tabanındaki netlerdedir.</p>
<div class="cell">
<details>
<summary>Kod</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>h <span class="ot">&lt;-</span> <span class="fu">which</span>(results<span class="sc">$</span>absfark<span class="sc">&gt;</span><span class="dv">5</span>)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">t</span>(modeldataTYT[h,<span class="sc">-</span><span class="fu">c</span>(<span class="dv">13</span><span class="sc">:</span><span class="dv">25</span>,<span class="dv">28</span>,<span class="dv">30</span>)]) <span class="sc">|&gt;</span> <span class="fu">kbl</span>()</span></code><button title="Panoya Kopyala" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table>
<tbody>
  <tr>
   <td style="text-align:left;"> ProgramKodu </td>
   <td style="text-align:left;"> 206550021 </td>
   <td style="text-align:left;"> 200351003 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Üniversite </td>
   <td style="text-align:left;"> ÜSKÜDAR ÜNİV.  - (Burslu) (2 Yıllık) </td>
   <td style="text-align:left;"> AVRASYA ÜNİV.  - (Burslu) (2 Yıllık) </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Yılı </td>
   <td style="text-align:left;"> 2021 </td>
   <td style="text-align:left;"> 2021 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Türü </td>
   <td style="text-align:left;"> Vakıf </td>
   <td style="text-align:left;"> Vakıf </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Katsayı </td>
   <td style="text-align:left;"> 0.12 </td>
   <td style="text-align:left;"> 0.12 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> OBP </td>
   <td style="text-align:left;"> 382.649 </td>
   <td style="text-align:left;"> 369.700 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Puan </td>
   <td style="text-align:left;"> 270.4194 </td>
   <td style="text-align:left;"> 259.9283 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Yerl. </td>
   <td style="text-align:left;"> 12 </td>
   <td style="text-align:left;"> 9 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> TYT Türkçe </td>
   <td style="text-align:left;"> 24.25 </td>
   <td style="text-align:left;"> 19.50 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> TYT Sosyal </td>
   <td style="text-align:left;"> 15.25 </td>
   <td style="text-align:left;"> 9.25 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> TYT Mat </td>
   <td style="text-align:left;"> 0.75 </td>
   <td style="text-align:left;"> 2.00 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> TYT Fen </td>
   <td style="text-align:left;"> 0.0 </td>
   <td style="text-align:left;"> 2.5 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> PuanTuru </td>
   <td style="text-align:left;"> TYT </td>
   <td style="text-align:left;"> TYT </td>
  </tr>
  <tr>
   <td style="text-align:left;"> BoluMKodu </td>
   <td style="text-align:left;"> 30146 </td>
   <td style="text-align:left;"> 30151 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> SinavPuan </td>
   <td style="text-align:left;"> 224.5015 </td>
   <td style="text-align:left;"> 215.5643 </td>
  </tr>
</tbody>
</table>

</div>
</div>
<p>Bu gözlemler veriden çıkarıp model katsayıları tekrar hesaplanıyor. Artık modelde hata yok. Model veriyi %100 oranında açıklıyor. TYT sınavına giren öğrencilerin başarılarına göre standardize edilen soru gruplarının puan karşılıkları regresyon modelinin katsayıları olarak bulundu.</p>
<p>OSYM tarafından eklenen 100 puan çeşitli transformasyonlar sonucu 97.34’e düşmüştür. Her soru grubunun puanlamaya etkisi regresyon modelinin katsayılarında temsil edilmektedir. Buna göre en değerli sorular Matematik sorularıdır. Her matematik neti 4.53 puan anlamına gelmektedir. 2021 yılı için ikinci sırada en değerli puanların Fen Bilimleri soru grubunda olduğu görülmektedir. Bir fen bilimleri neti 3.18 puana denk gelmektedir. Türkçe ve Sosyal bilimler sorularının puanları yaklaşık olarak aynıdır. Grafikte soru gruplarının ağırlıkları görsel olarak ifade edilmiştir. Yıldan yıla bu katsayılar sınava katılan öğrencilerin performansına bağlı olarak değişmektedir. Bir soru grubunda Türkiye genelinde az başarılı olunursa bu soru grubunun değeri artmaktadır. Burada amaç öğrencileri birbirinden mümkün olduğunca ayırabilmektir.</p>
<div class="cell">
<details>
<summary>Kod</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>modeldataTYT1 <span class="ot">&lt;-</span> modeldataTYT[<span class="sc">-</span>h,]</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>TYTModel <span class="ot">&lt;-</span> <span class="fu">lm</span>(SinavPuan<span class="sc">~</span><span class="st">`</span><span class="at">TYT Mat</span><span class="st">`</span><span class="sc">+</span><span class="st">`</span><span class="at">TYT Türkçe</span><span class="st">`</span><span class="sc">+</span><span class="st">`</span><span class="at">TYT Fen</span><span class="st">`</span><span class="sc">+</span><span class="st">`</span><span class="at">TYT Sosyal</span><span class="st">`</span>, <span class="at">data=</span>modeldataTYT1)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summ</span>(TYTModel,<span class="at">digits =</span> <span class="dv">5</span>)</span></code><button title="Panoya Kopyala" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="table table-striped table-hover table-condensed table-responsive" style="width: auto !important; margin-left: auto; margin-right: auto;">
<tbody>
  <tr>
   <td style="text-align:left;font-weight: bold;"> Observations </td>
   <td style="text-align:right;"> 2318 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> Dependent variable </td>
   <td style="text-align:right;"> SinavPuan </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> Type </td>
   <td style="text-align:right;"> OLS linear regression </td>
  </tr>
</tbody>
</table> <table class="table table-striped table-hover table-condensed table-responsive" style="width: auto !important; margin-left: auto; margin-right: auto;">
<tbody>
  <tr>
   <td style="text-align:left;font-weight: bold;"> F(4,2313) </td>
   <td style="text-align:right;"> 365033785663367.31250 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> R² </td>
   <td style="text-align:right;"> 1.00000 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> Adj. R² </td>
   <td style="text-align:right;"> 1.00000 </td>
  </tr>
</tbody>
</table> <table class="table table-striped table-hover table-condensed table-responsive" style="width: auto !important; margin-left: auto; margin-right: auto;border-bottom: 0;">
 <thead>
  <tr>
   <th style="text-align:left;">   </th>
   <th style="text-align:right;"> Est. </th>
   <th style="text-align:right;"> S.E. </th>
   <th style="text-align:right;"> t val. </th>
   <th style="text-align:right;"> p </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;font-weight: bold;"> (Intercept) </td>
   <td style="text-align:right;"> 97.33911 </td>
   <td style="text-align:right;"> 0.00000 </td>
   <td style="text-align:right;"> 40877845.52738 </td>
   <td style="text-align:right;"> 0.00000 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> `TYT Mat` </td>
   <td style="text-align:right;"> 4.52956 </td>
   <td style="text-align:right;"> 0.00000 </td>
   <td style="text-align:right;"> 16333594.42471 </td>
   <td style="text-align:right;"> 0.00000 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> `TYT Türkçe` </td>
   <td style="text-align:right;"> 2.92085 </td>
   <td style="text-align:right;"> 0.00000 </td>
   <td style="text-align:right;"> 21686245.09984 </td>
   <td style="text-align:right;"> 0.00000 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> `TYT Fen` </td>
   <td style="text-align:right;"> 3.18450 </td>
   <td style="text-align:right;"> 0.00000 </td>
   <td style="text-align:right;"> 8700242.49859 </td>
   <td style="text-align:right;"> 0.00000 </td>
  </tr>
  <tr>
   <td style="text-align:left;font-weight: bold;"> `TYT Sosyal` </td>
   <td style="text-align:right;"> 2.97902 </td>
   <td style="text-align:right;"> 0.00000 </td>
   <td style="text-align:right;"> 12374553.77474 </td>
   <td style="text-align:right;"> 0.00000 </td>
  </tr>
</tbody>
<tfoot><tr><td style="padding: 0; " colspan="100%">
<sup></sup> Standard errors: OLS</td></tr></tfoot>
</table>
</div>
<details>
<summary>Kod</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_summs</span>(TYTModel)</span></code><button title="Panoya Kopyala" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="puan_hesaplama_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="672"></p>
</div>
<details>
<summary>Kod</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>results <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">real =</span> modeldataTYT1<span class="sc">$</span>SinavPuan,<span class="at">model=</span><span class="fu">predict</span>(TYTModel))</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>results<span class="sc">$</span>fark <span class="ot">&lt;-</span> results<span class="sc">$</span>real<span class="sc">-</span>results<span class="sc">$</span>model</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>results<span class="sc">$</span>absfark <span class="ot">&lt;-</span> <span class="fu">abs</span>(results<span class="sc">$</span>real<span class="sc">-</span>results<span class="sc">$</span>model)</span></code><button title="Panoya Kopyala" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Yıldan yıla bu katsayılar sınava katılan öğrencilerin performansına bağlı olarak değişmektedir. Bir soru grubunda Türkiye genelinde az başarılı olunursa bu soru grubunun değeri artmaktadır. Burada amaç öğrencileri birbirinden mümkün olduğunca ayırabilmektir.</p>
<div class="cell">
<details>
<summary>Kod</summary>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>TYTKatsayilar <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"TYTKatsayilar.csv"</span>)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>TYTKatsayilar <span class="sc">|&gt;</span> <span class="fu">kbl</span>(<span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Soru Grubu"</span>, <span class="st">"2019"</span>,<span class="st">"2020"</span>,<span class="st">"2021"</span>),<span class="at">booktabs =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span> </span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>()</span></code><button title="Panoya Kopyala" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="table" style="margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:left;"> Soru Grubu </th>
   <th style="text-align:right;"> 2019 </th>
   <th style="text-align:right;"> 2020 </th>
   <th style="text-align:right;"> 2021 </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> Matematik </td>
   <td style="text-align:right;"> 3.72544 </td>
   <td style="text-align:right;"> 3.34392 </td>
   <td style="text-align:right;"> 4.529560 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Türkçe </td>
   <td style="text-align:right;"> 3.10474 </td>
   <td style="text-align:right;"> 3.24011 </td>
   <td style="text-align:right;"> 2.920850 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Fen Bilimleri </td>
   <td style="text-align:right;"> 3.49299 </td>
   <td style="text-align:right;"> 3.40551 </td>
   <td style="text-align:right;"> 3.184504 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Sosyal Bilimler </td>
   <td style="text-align:right;"> 3.02917 </td>
   <td style="text-align:right;"> 3.65789 </td>
   <td style="text-align:right;"> 2.979017 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> SABİT </td>
   <td style="text-align:right;"> 100.06900 </td>
   <td style="text-align:right;"> 99.42090 </td>
   <td style="text-align:right;"> 97.339196 </td>
  </tr>
</tbody>
</table>

</div>
</div>
<div class="cell">

</div>


</section>
</section>
</section>


<div id="quarto-appendix" class="default"><section class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Dipnotlar</h2>

<ol>
<li id="fn1" role="doc-endnote"><p>SAY, EA, SÖZ, DİL, TYT<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2" role="doc-endnote"><p>Tabloda görülmemesine rağmen aslında yüklenen sayfada puanların da bulunduğunu görmek için sayfanın kaynak koduna bakılabilir.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3" role="doc-endnote"><p><a href="https://yokatlas.yok.gov.tr/2020/netler-tablo.php?b=19001" class="uri">https://yokatlas.yok.gov.tr/2020/netler-tablo.php?b=19001</a><a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4" role="doc-endnote"><p>Regresyon modeli hemen her lisans programında gösterilen en temel istatistiki modeldir.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section><section class="quarto-appendix-contents"><h2 class="anchored quarto-appendix-heading">Yeniden kullanın</h2><div quarto-reuse="quarto-reuse" class="quarto-appendix-contents"><a rel="license" href="https://creativecommons.org/licenses/by/4.0/deed.tr">https://creativecommons.org/licenses/by/4.0/deed.tr</a></div></section><section class="quarto-appendix-contents"><h2 class="anchored quarto-appendix-heading">Alıntı</h2><div><div class="quarto-appendix-secondary-label">BibTeX</div><pre class="sourceCode code-with-copy quarto-appendix-bibtex"><code class="sourceCode bibtex">@online{serkanalbayrak2022,
  author = {Raif Serkan Albayrak},
  title = {YKS Puanı Hesaplama Formülleri},
  date = {2022-05-31},
  langid = {tr}
}
</code><button title="Panoya Kopyala" class="code-copy-button"><i class="bi"></i></button></pre><div class="quarto-appendix-secondary-label">Lütfen bu çalışmayı şu şekilde alıntılayın:</div><div id="ref-serkanalbayrak2022" class="csl-entry quarto-appendix-citeas" role="doc-biblioentry">
Raif Serkan Albayrak. 2022. <span>“YKS Puanı Hesaplama
Formülleri.”</span> May 31, 2022.
</div></div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Kopyalandı");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->



</body></html>